### ISSUE TITLE
Address cucmcn1c variable present in commercial dataset

### ISSUE THREAD

**Issue by mcailler** [sleepepi/mesa-data-dictionary#12]
Variable was added to filter participants who did not consent to have their data shared commercially; currently the variable is present in the CSV file, but their is no corresponding JSON file. Do we strip it from the dataset (as it's 'Yes' for all participants) or do we add a JSON variable for it? @mrueschman 

@remomueller – either way, when I do the new one does it get tagged `v01.1.commercial.2`?

**Comment by mcailler** [comment]
Sounds like we'll be adding cucmcn1c to the noncommercial dataset as well and creating a JSON variable file for it in commercial

**Comment by remomueller** [comment]
Sounds good to me to keep the variable in the dataset, to keep the two datasets as consistent as possible.
